### ISSUE TITLE
[Bug] 无法正常使用箱子内物品来制造

### ISSUE THREAD

**Issue by txyyh** [Breathe97/extra-equip-slot-eqs#2]
**问题描述**

开启本 mod 后，如果身上没有对应物品，则无法正常使用箱子内物品进行制造。
举例，如果人物身上有燧石，那么他可以正常使用箱子内的燧石来制作斧头；但如果人物身上没有燧石，而箱子里有，就无法使用箱子内的物品正常制作斧头。

设置中开启了融合背包布局，已在纯净档测试。

![图片](https://user-images.githubusercontent.com/41893946/227153814-39f98099-2892-4d35-abf8-c43401313078.png)

**log**

[server_log.txt](https://github.com/Breathe97/extra-equip-slot-eqs/files/11048951/server_log.txt)
[client_log.txt](https://github.com/Breathe97/extra-equip-slot-eqs/files/11048952/client_log.txt)

**版本相关**

饥荒联机版：v548857(64-bit)

mod 版本：【3 月 22 日 下午 8:25】 更新版本

系统版本： Windows 11 22H2，内部版本 22621.1413

设备：华硕笔记本 无畏 Pro 14 (M3400QA)

CPU：AMD Ryzen 7 5800H

GPU：核显，无独显

**Comment by Breathe97** [comment]
![image](https://user-images.githubusercontent.com/49851873/227184865-f9b6153c-da27-4d07-ab8b-f87093129372.png)
我本地还是没有发现这个问题 你用其他模组或者不开模组试试还会出现这个问题吗。我复现不了这个问题 我就不好去解决。

**Comment by Breathe97** [comment]
![image](https://user-images.githubusercontent.com/49851873/227187726-5869c578-c737-4da2-8667-f1e33e744ad4.png)

**Comment by txyyh** [comment]
我测试前是特意关了mod去测试
您使用的是64位的吗

**Comment by txyyh** [comment]
我自己意思是64位的饥荒

刚验证了游戏完整性，但修复后还是一样有问题

同类的话，4/5/6格装备栏 是完全正常的


mod 已经全部关闭了，测试的时候本地mod和其他的服务器mod都没开

**Comment by Breathe97** [comment]
@txyyh  感谢您的测试 足够让我确信是我的模组导致的问题，我查阅了游戏源码，并尝试着修复，但是因为我本地的机器是测试不了的，我推送了1.1.5分支，如果您愿意的话可以下载后把他放到游戏目录中试一下。
例如将下载后的整个extra-equip-slot-eqs 文件夹 放入D:\Steam\steamapps\common\Don't Starve Together\mods，前面的路径需要你自己判断一下是哪里，如果不清楚的话，你可以在steam中右键游戏->管理->浏览本地文件，然后就可以找到mods文件夹了

**Comment by Breathe97** [comment]
已解决。
