### ISSUE TITLE
[Bug] shift+左键无法快捷移动物品到背包

### ISSUE THREAD

**Issue by txyyh** [Breathe97/extra-equip-slot-eqs#3]
**问题描述**

如图，当物品栏占满时，无法使用 shift+左键将物品移动到背包。
并且也无法使用此方法将物品栏物品移动到背包

![图片](https://user-images.githubusercontent.com/41893946/227157513-97189ed0-2849-4f61-81f5-294443b83574.png)

**log**
[server_log.txt](https://github.com/Breathe97/extra-equip-slot-eqs/files/11049104/server_log.txt)
[client_log.txt](https://github.com/Breathe97/extra-equip-slot-eqs/files/11049103/client_log.txt)

**版本相关**

饥荒联机版：v548857(64-bit)

mod 版本：【3 月 22 日 下午 8:25】 更新版本

系统版本： Windows 11 22H2，内部版本 22621.1413

设备：华硕笔记本 无畏 Pro 14 (M3400QA)

CPU：AMD Ryzen 7 5800H

GPU：核显，无独显

**Comment by Breathe97** [comment]
我大概知道问题原因了 你把背包栏改成分离式看看还存在这个问题不，因为我一直都喜欢用分离式的背包栏 所以没发现这个情况

**Comment by Breathe97** [comment]
等会下班了我回去看一下

**Comment by Breathe97** [comment]
这个问题我本地也复现不了，你可以试一下不开模组还会有这个问题吗？会不会是因为游戏本体损坏导致的呢

**Comment by Breathe97** [comment]
现已解决，关闭了哈。
